(cl:defpackage custom_msgs-msg
  (:use )
  (:export
   "<RENDERERPOLYLINETRI>"
   "RENDERERPOLYLINETRI"
   "<STAMPEDFRAMES>"
   "STAMPEDFRAMES"
   "<STAMPEDMATCHESWITHIMAGE>"
   "STAMPEDMATCHESWITHIMAGE"
   "<DESCRIBEDPOINTCLOUD>"
   "DESCRIBEDPOINTCLOUD"
   "<STAMPEDFEATURESWITHIMAGE>"
   "STAMPEDFEATURESWITHIMAGE"
   "<STAMPEDFEATURESMATCHESWITHIMAGE>"
   "STAMPEDFEATURESMATCHESWITHIMAGE"
   "<STAMPEDSTAMPEDINT>"
   "STAMPEDSTAMPEDINT"
   "<STAMPEDFEATURESMATCHES>"
   "STAMPEDFEATURESMATCHES"
  ))

