/* Auto-generated by genmsg_cpp for file /home/alex/cued-ardrone/custom_msgs/msg/DescribedPointCloud.msg */
#ifndef CUSTOM_MSGS_MESSAGE_DESCRIBEDPOINTCLOUD_H
#define CUSTOM_MSGS_MESSAGE_DESCRIBEDPOINTCLOUD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace custom_msgs
{
template <class ContainerAllocator>
struct DescribedPointCloud_ {
  typedef DescribedPointCloud_<ContainerAllocator> Type;

  DescribedPointCloud_()
  : header()
  , cloud_points()
  , descriptors()
  , descriptors_stride(0)
  , descriptors_matcher()
  , points()
  {
  }

  DescribedPointCloud_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , cloud_points(_alloc)
  , descriptors(_alloc)
  , descriptors_stride(0)
  , descriptors_matcher(_alloc)
  , points(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _cloud_points_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  cloud_points;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _descriptors_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  descriptors;

  typedef int16_t _descriptors_stride_type;
  int16_t descriptors_stride;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _descriptors_matcher_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  descriptors_matcher;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  points;


  typedef boost::shared_ptr< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::DescribedPointCloud_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DescribedPointCloud
typedef  ::custom_msgs::DescribedPointCloud_<std::allocator<void> > DescribedPointCloud;

typedef boost::shared_ptr< ::custom_msgs::DescribedPointCloud> DescribedPointCloudPtr;
typedef boost::shared_ptr< ::custom_msgs::DescribedPointCloud const> DescribedPointCloudConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::custom_msgs::DescribedPointCloud_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::DescribedPointCloud_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fbbef13ecabc7cecbc61dcc36adea686";
  }

  static const char* value(const  ::custom_msgs::DescribedPointCloud_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfbbef13ecabc7cecULL;
  static const uint64_t static_value2 = 0xbc61dcc36adea686ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > {
  static const char* value() 
  {
    return "custom_msgs/DescribedPointCloud";
  }

  static const char* value(const  ::custom_msgs::DescribedPointCloud_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32[] cloud_points\n\
float32[] descriptors\n\
int16 descriptors_stride\n\
string descriptors_matcher\n\
float32[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::custom_msgs::DescribedPointCloud_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::custom_msgs::DescribedPointCloud_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.cloud_points);
    stream.next(m.descriptors);
    stream.next(m.descriptors_stride);
    stream.next(m.descriptors_matcher);
    stream.next(m.points);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DescribedPointCloud_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::DescribedPointCloud_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::custom_msgs::DescribedPointCloud_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cloud_points[]" << std::endl;
    for (size_t i = 0; i < v.cloud_points.size(); ++i)
    {
      s << indent << "  cloud_points[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cloud_points[i]);
    }
    s << indent << "descriptors[]" << std::endl;
    for (size_t i = 0; i < v.descriptors.size(); ++i)
    {
      s << indent << "  descriptors[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.descriptors[i]);
    }
    s << indent << "descriptors_stride: ";
    Printer<int16_t>::stream(s, indent + "  ", v.descriptors_stride);
    s << indent << "descriptors_matcher: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.descriptors_matcher);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DESCRIBEDPOINTCLOUD_H

