/* Auto-generated by genmsg_cpp for file /home/alex/cued-ardrone/custom_msgs/msg/StampedMatchesWithImage.msg */
#ifndef CUSTOM_MSGS_MESSAGE_STAMPEDMATCHESWITHIMAGE_H
#define CUSTOM_MSGS_MESSAGE_STAMPEDMATCHESWITHIMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "sensor_msgs/Image.h"

namespace custom_msgs
{
template <class ContainerAllocator>
struct StampedMatchesWithImage_ {
  typedef StampedMatchesWithImage_<ContainerAllocator> Type;

  StampedMatchesWithImage_()
  : header()
  , pts()
  , image()
  {
  }

  StampedMatchesWithImage_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pts(_alloc)
  , image(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pts_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  pts;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  image;


  typedef boost::shared_ptr< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StampedMatchesWithImage
typedef  ::custom_msgs::StampedMatchesWithImage_<std::allocator<void> > StampedMatchesWithImage;

typedef boost::shared_ptr< ::custom_msgs::StampedMatchesWithImage> StampedMatchesWithImagePtr;
typedef boost::shared_ptr< ::custom_msgs::StampedMatchesWithImage const> StampedMatchesWithImageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "11315e55547abf288909d784e74e3315";
  }

  static const char* value(const  ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x11315e55547abf28ULL;
  static const uint64_t static_value2 = 0x8909d784e74e3315ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "custom_msgs/StampedMatchesWithImage";
  }

  static const char* value(const  ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32[] pts\n\
sensor_msgs/Image image\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in src/image_encodings.cpp\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
";
  }

  static const char* value(const  ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pts);
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StampedMatchesWithImage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::custom_msgs::StampedMatchesWithImage_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pts[]" << std::endl;
    for (size_t i = 0; i < v.pts.size(); ++i)
    {
      s << indent << "  pts[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pts[i]);
    }
    s << indent << "image: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_STAMPEDMATCHESWITHIMAGE_H

