/* Auto-generated by genmsg_cpp for file /home/alex/cued-ardrone/custom_msgs/msg/StampedFeaturesMatches.msg */
#ifndef CUSTOM_MSGS_MESSAGE_STAMPEDFEATURESMATCHES_H
#define CUSTOM_MSGS_MESSAGE_STAMPEDFEATURESMATCHES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "std_msgs/Header.h"

namespace custom_msgs
{
template <class ContainerAllocator>
struct StampedFeaturesMatches_ {
  typedef StampedFeaturesMatches_<ContainerAllocator> Type;

  StampedFeaturesMatches_()
  : header1()
  , header2()
  , points1()
  , points2()
  , descriptors1()
  , descriptors2()
  , descriptors_stride(0)
  , descriptors_matcher()
  , F()
  , P1()
  , P2()
  {
  }

  StampedFeaturesMatches_(const ContainerAllocator& _alloc)
  : header1(_alloc)
  , header2(_alloc)
  , points1(_alloc)
  , points2(_alloc)
  , descriptors1(_alloc)
  , descriptors2(_alloc)
  , descriptors_stride(0)
  , descriptors_matcher(_alloc)
  , F(_alloc)
  , P1(_alloc)
  , P2(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header1_type;
   ::std_msgs::Header_<ContainerAllocator>  header1;

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header2_type;
   ::std_msgs::Header_<ContainerAllocator>  header2;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points1_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  points1;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _points2_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  points2;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _descriptors1_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  descriptors1;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _descriptors2_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  descriptors2;

  typedef int16_t _descriptors_stride_type;
  int16_t descriptors_stride;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _descriptors_matcher_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  descriptors_matcher;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _F_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  F;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _P1_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  P1;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _P2_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  P2;


  typedef boost::shared_ptr< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StampedFeaturesMatches
typedef  ::custom_msgs::StampedFeaturesMatches_<std::allocator<void> > StampedFeaturesMatches;

typedef boost::shared_ptr< ::custom_msgs::StampedFeaturesMatches> StampedFeaturesMatchesPtr;
typedef boost::shared_ptr< ::custom_msgs::StampedFeaturesMatches const> StampedFeaturesMatchesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cbc18a10678a1e1ce89ac8ea4e4d22c4";
  }

  static const char* value(const  ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcbc18a10678a1e1cULL;
  static const uint64_t static_value2 = 0xe89ac8ea4e4d22c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> > {
  static const char* value() 
  {
    return "custom_msgs/StampedFeaturesMatches";
  }

  static const char* value(const  ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header1\n\
Header header2\n\
float32[] points1\n\
float32[] points2\n\
float32[] descriptors1\n\
float32[] descriptors2\n\
int16 descriptors_stride\n\
string descriptors_matcher\n\
float32[] F\n\
float32[] P1\n\
float32[] P2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header1);
    stream.next(m.header2);
    stream.next(m.points1);
    stream.next(m.points2);
    stream.next(m.descriptors1);
    stream.next(m.descriptors2);
    stream.next(m.descriptors_stride);
    stream.next(m.descriptors_matcher);
    stream.next(m.F);
    stream.next(m.P1);
    stream.next(m.P2);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StampedFeaturesMatches_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::custom_msgs::StampedFeaturesMatches_<ContainerAllocator> & v) 
  {
    s << indent << "header1: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header1);
    s << indent << "header2: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header2);
    s << indent << "points1[]" << std::endl;
    for (size_t i = 0; i < v.points1.size(); ++i)
    {
      s << indent << "  points1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points1[i]);
    }
    s << indent << "points2[]" << std::endl;
    for (size_t i = 0; i < v.points2.size(); ++i)
    {
      s << indent << "  points2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points2[i]);
    }
    s << indent << "descriptors1[]" << std::endl;
    for (size_t i = 0; i < v.descriptors1.size(); ++i)
    {
      s << indent << "  descriptors1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.descriptors1[i]);
    }
    s << indent << "descriptors2[]" << std::endl;
    for (size_t i = 0; i < v.descriptors2.size(); ++i)
    {
      s << indent << "  descriptors2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.descriptors2[i]);
    }
    s << indent << "descriptors_stride: ";
    Printer<int16_t>::stream(s, indent + "  ", v.descriptors_stride);
    s << indent << "descriptors_matcher: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.descriptors_matcher);
    s << indent << "F[]" << std::endl;
    for (size_t i = 0; i < v.F.size(); ++i)
    {
      s << indent << "  F[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.F[i]);
    }
    s << indent << "P1[]" << std::endl;
    for (size_t i = 0; i < v.P1.size(); ++i)
    {
      s << indent << "  P1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.P1[i]);
    }
    s << indent << "P2[]" << std::endl;
    for (size_t i = 0; i < v.P2.size(); ++i)
    {
      s << indent << "  P2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.P2[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_STAMPEDFEATURESMATCHES_H

