/* Auto-generated by genmsg_cpp for file /home/alex/cued-ardrone/custom_msgs/msg/StampedStampedInt.msg */
#ifndef CUSTOM_MSGS_MESSAGE_STAMPEDSTAMPEDINT_H
#define CUSTOM_MSGS_MESSAGE_STAMPEDSTAMPEDINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "std_msgs/Header.h"

namespace custom_msgs
{
template <class ContainerAllocator>
struct StampedStampedInt_ {
  typedef StampedStampedInt_<ContainerAllocator> Type;

  StampedStampedInt_()
  : header1()
  , header2()
  , count(0)
  {
  }

  StampedStampedInt_(const ContainerAllocator& _alloc)
  : header1(_alloc)
  , header2(_alloc)
  , count(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header1_type;
   ::std_msgs::Header_<ContainerAllocator>  header1;

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header2_type;
   ::std_msgs::Header_<ContainerAllocator>  header2;

  typedef int16_t _count_type;
  int16_t count;


  typedef boost::shared_ptr< ::custom_msgs::StampedStampedInt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::StampedStampedInt_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StampedStampedInt
typedef  ::custom_msgs::StampedStampedInt_<std::allocator<void> > StampedStampedInt;

typedef boost::shared_ptr< ::custom_msgs::StampedStampedInt> StampedStampedIntPtr;
typedef boost::shared_ptr< ::custom_msgs::StampedStampedInt const> StampedStampedIntConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::custom_msgs::StampedStampedInt_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::custom_msgs::StampedStampedInt_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::StampedStampedInt_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::custom_msgs::StampedStampedInt_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::StampedStampedInt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "456f6e7b11f035fb268f51b6a451715b";
  }

  static const char* value(const  ::custom_msgs::StampedStampedInt_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x456f6e7b11f035fbULL;
  static const uint64_t static_value2 = 0x268f51b6a451715bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::StampedStampedInt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "custom_msgs/StampedStampedInt";
  }

  static const char* value(const  ::custom_msgs::StampedStampedInt_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::StampedStampedInt_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header1\n\
Header header2\n\
int16 count\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::custom_msgs::StampedStampedInt_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::custom_msgs::StampedStampedInt_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header1);
    stream.next(m.header2);
    stream.next(m.count);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StampedStampedInt_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::StampedStampedInt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::custom_msgs::StampedStampedInt_<ContainerAllocator> & v) 
  {
    s << indent << "header1: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header1);
    s << indent << "header2: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header2);
    s << indent << "count: ";
    Printer<int16_t>::stream(s, indent + "  ", v.count);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_STAMPEDSTAMPEDINT_H

