(cl:defpackage ardrone_autonomy-srv
  (:use )
  (:export
   "HULLSELECT"
   "<HULLSELECT-REQUEST>"
   "HULLSELECT-REQUEST"
   "<HULLSELECT-RESPONSE>"
   "HULLSELECT-RESPONSE"
   "CAMSELECT"
   "<CAMSELECT-REQUEST>"
   "CAMSELECT-REQUEST"
   "<CAMSELECT-RESPONSE>"
   "CAMSELECT-RESPONSE"
   "LEDANIM"
   "<LEDANIM-REQUEST>"
   "LEDANIM-REQUEST"
   "<LEDANIM-RESPONSE>"
   "LEDANIM-RESPONSE"
  ))

