(cl:defpackage dynamics-srv
  (:use )
  (:export
   "CAMSELECT"
   "<CAMSELECT-REQUEST>"
   "CAMSELECT-REQUEST"
   "<CAMSELECT-RESPONSE>"
   "CAMSELECT-RESPONSE"
   "HULLSELECT"
   "<HULLSELECT-REQUEST>"
   "HULLSELECT-REQUEST"
   "<HULLSELECT-RESPONSE>"
   "HULLSELECT-RESPONSE"
   "CAPTURE_IMAGE_FEATURES"
   "<CAPTURE_IMAGE_FEATURES-REQUEST>"
   "CAPTURE_IMAGE_FEATURES-REQUEST"
   "<CAPTURE_IMAGE_FEATURES-RESPONSE>"
   "CAPTURE_IMAGE_FEATURES-RESPONSE"
   "LEDANIM"
   "<LEDANIM-REQUEST>"
   "LEDANIM-REQUEST"
   "<LEDANIM-RESPONSE>"
   "LEDANIM-RESPONSE"
  ))

